// Generated by `npm run pinterest` in the site builder: edit scripts/pinterest-release.mjs there instead.
// Run every morning by .github/workflows/pinterest.yml. Releases the next pins from queue.json into one RSS feed
// per board (pinterest/<board>.xml), which Pinterest reads daily and posts as new pins.
// Works out everything from the date, so running it twice in a day changes nothing.
// When a board runs out of pins it starts again from its first one.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const DOMAIN = "https://1000errors.uk";
const KEEP_DAYS = 7; // feeds list the last week's pins, in case Pinterest misses a day
const DAY = 86400000;

const queue = JSON.parse(fs.readFileSync(path.join(here, "queue.json"), "utf8"));
const start = Date.parse(queue.start + "T00:00:00Z");
const today = Math.floor((Date.now() - start) / DAY); // 0 on the first day
const keys = Object.keys(queue.boards);

// Every pin released so far, in order: each one goes to the board furthest behind its share.
const released = Object.fromEntries(keys.map(k => [k, []]));
const counts = Object.fromEntries(keys.map(k => [k, 0]));
for (let i = 0; i < queue.perDay * (today + 1); i++) {
  const key = keys.reduce((best, k) => {
    const behind = b => queue.boards[b].share * (i + 1) - counts[b];
    return behind(k) > behind(best) ? k : best;
  });
  const pins = queue.boards[key].pins;
  const n = counts[key]++;
  if (!pins.length) continue;
  const day = Math.floor(i / queue.perDay);
  if (day <= today - KEEP_DAYS) continue;
  const round = Math.floor(n / pins.length);
  released[key].push({ ...pins[n % pins.length], guid: pins[n % pins.length].id + (round ? `-r${round}` : ""), date: new Date(start + day * DAY + 6 * 3600000) });
}

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
for (const key of keys) {
  const board = queue.boards[key];
  const items = released[key].reverse().map(p => {
    const link = `${p.link}?utm_source=pinterest&utm_medium=social&utm_campaign=${key}&utm_content=${p.guid}`;
    return `  <item>
    <title>${esc(p.title)}</title>
    <link>${esc(link)}</link>
    <description>${esc(p.description)}</description>
    <guid isPermaLink="false">${esc(p.guid)}</guid>
    <pubDate>${p.date.toUTCString()}</pubDate>
    <enclosure url="${esc(p.image)}" length="${p.bytes}" type="image/jpeg" />
    <media:content url="${esc(p.image)}" medium="image" type="image/jpeg" />
  </item>`;
  });
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
  <title>${esc(`1000 Errors: ${board.name}`)}</title>
  <link>${DOMAIN}/</link>
  <description>${esc(`${board.name} by 1000 Errors.`)}</description>
  <atom:link href="${DOMAIN}/pinterest/${key}.xml" rel="self" type="application/rss+xml" />
${items.join("\n")}
</channel>
</rss>
`;
  const file = path.join(here, `${key}.xml`);
  if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== xml) fs.writeFileSync(file, xml);
  console.log(`  ${key.padEnd(22)} ${items.length} pins in the feed`);
}
